name: Setup

defaults:
  run:
    shell: bash

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js and pnpm
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: pnpm
        registry-url: https://registry.npmjs.org
    - name: Install dependencies
      run: pnpm install