name: Publish to npmjs
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Download latest release asset
        id: download_release
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          fileName: '*.tgz'
      - name: Publish
        run: pnpm publish --access public ${{ fromJson(steps.download_release.outputs.downloaded_files)[0] }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true