name: Create a GitHub Release and publish to npmjs

on:
  push:
    tags:
      - "v*"

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./packages/nextjs

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Tests
        uses: ./.github/actions/tests
      - name: Build
        run: pnpm build
      - name: Pack
        run: pnpm pack --pack-destination release
      - name: Create GitHub Release
        uses: ghalactic/github-release-from-tag@v5
        with:
          prerelease: false
          assets: |
            - path: packages/nextjs/release/*.tgz
      - name: Publish to npmjs
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true