name: Create a GitHub Release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        run: pnpm build
      - name: Pack
        run: pnpm pack --pack-destination release
      - name: Publish release
        uses: ghalactic/github-release-from-tag@v5
        with:
          assets: |
            - path: release/*