name: Create a tag
on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Create Tag
        uses: salsify/action-detect-and-tag-new-version@v2